version: '3.8'

services:
  server:
    image: nginx:stable-alpine
    #build:
    #  context: .
    #  dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf # ro -> read only
      # - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # ro -> read only
      - ./logs/nginx:/var/log/nginx/
    networks:
      - internal
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - internal

  mysql:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    #build:
    #  context: ./mysql
    #  dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    env_file:
      - ./env/mysql.env
    networks:
      - internal

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - internal

  artisan:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/usr/local/bin/php", "artisan"]
    networks:
      - internal

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge