version: "3.9"

networks:
  internal:
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - "8000:80"
    volumes:
      - ./logs/nginx:/var/log/nginx/
    networks:
      - internal
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    networks:
      - internal

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    env_file:
      - ./env/mysql.env
    networks:
      - internal

  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - internal

  artisan:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["/usr/local/bin/php", "artisan"]
    networks:
      - internal

  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes:
      - ./src:/var/www/html
    networks:
      - internal
